# Generated by Django 3.1.5 on 2022-01-13 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofile_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
