# Generated by Django 4.0.1 on 2022-01-20 15:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20220113_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=200)),
                ('post_date', models.DateField(default=datetime.datetime(2022, 1, 20, 21, 15, 29, 900190))),
                ('post_img', models.ImageField(upload_to='userposts')),
                ('likes', models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
