# Generated by Django 4.0.1 on 2022-01-29 15:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220121_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 29, 21, 9, 52, 86512)),
        ),
        migrations.CreateModel(
            name='Post_comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('comment_date', models.DateField(default=datetime.datetime(2022, 1, 29, 21, 9, 52, 86512))),
                ('comment_likes', models.ManyToManyField(to='home.UserProfile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.posts')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.post_comment')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile2userprofile', to='home.userprofile')),
            ],
        ),
    ]
