# Generated by Django 4.0.1 on 2022-01-29 15:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_posts_post_date_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='comment_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 29, 21, 16, 6, 684683)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.post_comment'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 29, 21, 16, 6, 684683)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='home.userprofile'),
        ),
    ]
